Repository BACKROOM-METINET/Mediation3D, pull requests merged in 2023-04, with the labels that each got.

#2 [Feat] web workers
  package-lock.json
  package.json
  src/client/class/hands.ts
  src/client/core.ts
  src/client/types/business.ts
  src/client/utils/converter.ts
  src/client/workers/pose-processing.ts
  src/components/NewUI/NewUI.vue
  src/stores/camera.ts
  src/stores/scene.ts
  tsconfig.vitest.json
Labels: ✨ feature

#5 [FIX] Holistic Optimization
  src/client/core.ts
  src/client/services/holistic.ts
  src/client/types/business.ts
  src/components/NewUI/NewUI.vue
Labels: 🛠️ fix

#7 [FIX] Camera lagging
  package-lock.json
  package.json
  src/client/workers/pose-processing.ts
  src/stores/scene.ts
Labels: 🛠️ fix

#9 [FEAT] Create visio part
  .env.template
  .gitignore
  package-lock.json
  package.json
  src/assets/main.css
  src/client/events/event.ts
  src/components/AddRoom/AddRoom.scss
  src/components/AddRoom/AddRoom.vue
  src/components/Log/Log.scss
  src/components/Log/Log.vue
  src/components/Rooms/Rooms.scss
  src/components/Rooms/Rooms.vue
  src/components/Video/Video.scss
  src/components/Video/Video.vue
  src/components/Visio/Visio.scss
  src/components/Visio/Visio.vue
  src/router/index.ts
Labels: ✨ feature

#10 [Fix] Camera Enabled without Holistic Activated
  src/components/Mediation/Mediation.scss
  src/components/MediationUI/MediationUI.scss
  src/components/MediationUI/MediationUI.vue
  src/components/icons/CameraOffIcon.vue
  src/stores/holistic.ts
Labels: 🛠️ fix

#11 [Fix] Mediation Options Menu
  package-lock.json
  src/components/MediationOptions/MediationOptions.scss
  src/components/MediationOptions/MediationOptions.vue
  src/stores/babylon-js/scene.ts
Labels: 🛠️ fix

#12 [Feat] Expression Recognition
  src/assets/base.css
  src/assets/img/emoji_angry.svg
  src/assets/img/emoji_happy.svg
  src/assets/img/emoji_neutral.svg
  src/assets/img/emoji_sad.svg
  src/assets/img/emoji_surprise.svg
  src/client/types/business.ts
  src/components/Mediation/Mediation.scss
  src/components/Mediation/Mediation.vue
  src/components/MediationUI/MediationUI.scss
  src/components/MediationUI/MediationUI.vue
  src/stores/holistic.ts
  src/stores/mediation.ts
Labels: ✨ feature

#13 [FIX] Remove useless console.log
  src/stores/mediation.ts
Labels: 🛠️ fix, ♻️ refactoring
