Repository BACKROOM-METINET/Mediation3D, pull requests merged in 2023-05, with the labels that each got.

#17 [FEAT] : Mediator create and join automatically room.
  src/client/client.ts
  src/client/types/emits.ts
  src/components/AddRoom/AddRoom.vue
  src/components/Rooms/Rooms.vue
  src/components/Video/Video.vue
  src/composables/emits.ts
Labels: ✨ feature, RFR

#18 Merge test into develop
  package-lock.json
  package.json
  src/App.vue
  src/client/client.ts
  src/client/types/business.ts
  src/client/types/emits.ts
  src/client/types/events.ts
  src/client/useLowLevelClient.ts
  src/components/AddRoom/AddRoom.vue
  src/components/Rooms/Rooms.vue
  src/components/Video/Video.vue
  src/components/Visio/Visio.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/router/index.ts
  src/stores/auth.ts
  src/stores/room.ts
Labels: ✨ feature, 🛠️ fix, RFR

#19 Add mediator interface + fix styles
  src/client/types/business.ts
  src/client/types/emits.ts
  src/components/AddRoom/AddRoom.vue
  src/components/Log/Log.scss
  src/components/Rooms/Rooms.scss
  src/components/Rooms/Rooms.vue
  src/components/Video/Video.scss
  src/components/Video/Video.vue
  src/components/Visio/Visio.scss
  src/composables/emits.ts
  src/stores/auth.ts
  src/stores/room.ts
Labels: ✨ feature, 🛠️ fix, RFR

#20 Multiple user in mediation + fix events
  src/App.vue
  src/client/client.ts
  src/client/helpers/mesh.ts
  src/client/types/business.ts
  src/client/types/emits.ts
  src/client/types/events.ts
  src/client/useLowLevelClient.ts
  src/client/workers/pose-processing.ts
  src/components/Mediation/Mediation.vue
  src/components/MediationUI/MediationUI.scss
  src/components/MediationUI/MediationUI.vue
  src/components/PreVisio/PreVisio.scss
  src/components/PreVisio/PreVisio.vue
  src/components/Visio/Visio.vue
  src/components/VisioAddRoom/VisioAddRoom.scss
  src/components/VisioAddRoom/VisioAddRoom.vue
  src/components/VisioLog/VisioLog.scss
  src/components/VisioLog/VisioLog.vue
  src/components/VisioRooms/VisioRooms.scss
  src/components/VisioRooms/VisioRooms.vue
  src/components/VisioVideo/VisioVideo.scss
  src/components/VisioVideo/VisioVideo.vue
  src/components/icons/ParticipantsIcon.vue
  src/composables/emits.ts
  src/composables/events.ts
  src/constants.ts
  src/router/index.ts
  src/stores/auth.ts
  src/stores/babylon-js/scene.ts
  src/stores/mediation.ts
  src/stores/room.ts
  src/views/HomeView.vue
Labels: ✨ feature, 🛠️ fix
